name: coo_charts
description: A flutter charts project for highly configurable professional charts.
version: 0.0.1+2
homepage: https://github.com/coodoo-io/coo_charts_demo # <- change this to the demo website
repository: https://github.com/coodoo-io/coo_charts
issue_tracker: https://github.com/coodoo-io/coo_charts/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  image: ^4.1.3
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter: